# Generated by Django 3.0.4 on 2020-06-20 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_type', models.CharField(choices=[('Standard_room', '标间'), ('Double_room', '大床房'), ('Couples_room', '情侣房'), ('Suite', '套房')], default='Standard_room', max_length=128)),
                ('is_check_in', models.BooleanField(default=False)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('gender', models.CharField(choices=[('man', '男'), ('woman', '女')], default='man', max_length=10)),
                ('phone', models.CharField(max_length=11)),
                ('id_card', models.CharField(max_length=18)),
                ('House_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.House')),
            ],
        ),
    ]
